# Use the official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 

# Copy the app code
COPY app.py .

# Expose port (optional for documentation)
EXPOSE  5000

# Run the app
CMD ["python", "app.py"]